### ISSUE TITLE
<br>, etc.

### ISSUE THREAD

**Issue by schmidhauser** [Arthur-Milchior/anki-html-src-in-field#2]
Thank you for sharing.

In my case at least, empty fields always show a `<br>` even if the fields themselves are empty. Could you hide these?

Also, in some cases one would like always to see the HTML code only: e.g., in the case of the Audio field, it happens not unoften that I have indeed a trailing, redundant `<br>` after the sound file (which will impact the field’s presentation), so it would be very useful if one could see this at once. Would there be a way to make one’s choice ‘sticky’?

**Comment by schmidhauser** [comment]
In my case, the `config` button does not show in the Addon Manager. And if one selects `true` in `config.json`, then it would be nice if one could go up and down in the Browser and (say) the Audio field would always show the source code.

I'm on macOS 10.14, with Anki 2.1.23.

**Comment by Arthur-Milchior** [comment]
I just downloaded the add-on and the "config" seems to work. Did you update the add-on recently (the initial version didn't have any configuration). I don't really understand what's wrong. Especially because the "config" button should appear if and only if there is a file "config.json" in the add-on folder. So there is no reason for you to see the file and not the button.
I'll concentrate on this problem first, because it should solve the problem of remembering your input.

**Comment by Arthur-Milchior** [comment]
If there are trailing br, there should be shown by the add-on. Can you please export a card with the bug you describe and share it with me, so that I can test myself.

**Comment by schmidhauser** [comment]
Regarding the `config` button, here’s a screenshot. (I have the newest version of the addon – I’ve just re-installed it.)

![html-source](https://user-images.githubusercontent.com/519178/77819139-cd002c00-7095-11ea-8590-ae94374935c0.jpg)

**Comment by Arthur-Milchior** [comment]
empty  fields does not show <br> anymore

**Comment by Arthur-Milchior** [comment]
and you downloaded it using ankiweb ?

**Comment by Arthur-Milchior** [comment]
Do the config button works with other add-on ? Because I've really no idea what is wrong here

**Comment by schmidhauser** [comment]
Now it works. I presume another addon prevented yours from displaying the `config` button and menu. I’m afraid I don’t know which one it was because I’ve just eliminated half a dozen or more.

And yes, I downloaded it from ankiweb.

![1-addon](https://user-images.githubusercontent.com/519178/77836510-f790ca00-7113-11ea-9db6-187f23052425.jpg)

**Comment by schmidhauser** [comment]
Regarding `<br>` in empty fields, here are two screenshots to illustrate what I mean:

![s1](https://user-images.githubusercontent.com/519178/77836525-17c08900-7114-11ea-8728-b562b3b31746.png)
![s2](https://user-images.githubusercontent.com/519178/77836528-18591f80-7114-11ea-9081-a5b9136e1607.png)

**Comment by Arthur-Milchior** [comment]
I assume you updated recently. it feels strange to me, because I thought I did solve the case on the right.
On the left, it's perfectly normal, sound tags remains sound tags, they are not interpreted in the field but when the card is rendered
